name: Karalių Skriptas
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # need this to access repo!
      - name: Rsync to VPS.
        env:
          KEY: ${{ secrets.SSH_KEY }}
          DESTINATION_PATH: ${{ secrets.DESTINATION_PATH }}
        run: |
          echo "Setting up private keys..."
          mkdir ~/.ssh
          echo "$KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          
          echo "github action rsync: $(date +%s)" > info
          
          echo "Trasnferring data..."
          rsync --progress -rvz -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" ${GITHUB_WORKSPACE}/html/* info "$DESTINATION_PATH"
