name: Karalių Skriptas
on:
  # thank you retards for renaming it to "main" branch :)))
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # need this to access repo!
      - name: rsync to vps
        env:
          KEY: ${{ secrets.SSH_KEY }}
          DESTINATION_PATH: ${{ secrets.DESTINATION_PATH }}
        run: |
          echo "setting up private keys..."
          mkdir ~/.ssh
          echo "$KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "github action rsync: $(date +%s)" > info
          echo "transferring data..."
          rsync --progress -rvz -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" ${GITHUB_WORKSPACE}/* "$DESTINATION_PATH"
